name: "prefect"

services:
  prefect:
    container_name: "prefect"
    image: prefecthq/prefect:2.19.9-python3.11
    env_file: "./.prefect.env"
    restart: unless-stopped
    entrypoint: ["prefect", "server", "start"]
    networks:
      - traefik
    expose: 
      - 4200
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.prefect-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.prefect.rule=Host(`workflows.example.com`)"
      - "traefik.http.services.prefect.loadbalancer.server.port=4200"
      - "traefik.http.routers.prefect-secure.rule=Host(`workflows.example.com`)"
      - "traefik.http.routers.prefect-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.prefect-secure.entrypoints=web-secure"
      - "traefik.http.routers.prefect.middlewares=prefect-redirect-web-secure"
      - "traefik.http.routers.prefect-secure.middlewares=oauth@file"
    depends_on:
      - oauth2-proxy
      - database

  database:
    image: postgres:16.3-alpine
    restart: always
    hostname: postgres
    env_file: ./.postgres.env
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    networks:
      - traefik
